// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw3KdpbyMS1IaUCy8z-xCThTOirjFeMmk',
    appId: '1:550306316768:web:d19417396acf8162ccab85',
    messagingSenderId: '550306316768',
    projectId: 'whatsaapold',
    authDomain: 'whatsaapold.firebaseapp.com',
    storageBucket: 'whatsaapold.appspot.com',
    measurementId: 'G-LTSY3LXPV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcPZ1A1FWo0TwLGgRjnr5iZW7p98Hf6U',
    appId: '1:550306316768:android:cf55739f8156b789ccab85',
    messagingSenderId: '550306316768',
    projectId: 'whatsaapold',
    storageBucket: 'whatsaapold.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnR9QM-6HyFsRwDBjX4CX9enWynZT_HQ',
    appId: '1:550306316768:ios:24f57b91920b5000ccab85',
    messagingSenderId: '550306316768',
    projectId: 'whatsaapold',
    storageBucket: 'whatsaapold.appspot.com',
    iosBundleId: 'com.deep.whatsaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYnR9QM-6HyFsRwDBjX4CX9enWynZT_HQ',
    appId: '1:550306316768:ios:24f57b91920b5000ccab85',
    messagingSenderId: '550306316768',
    projectId: 'whatsaapold',
    storageBucket: 'whatsaapold.appspot.com',
    iosBundleId: 'com.deep.whatsaap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw3KdpbyMS1IaUCy8z-xCThTOirjFeMmk',
    appId: '1:550306316768:web:e0a6a15282a7a239ccab85',
    messagingSenderId: '550306316768',
    projectId: 'whatsaapold',
    authDomain: 'whatsaapold.firebaseapp.com',
    storageBucket: 'whatsaapold.appspot.com',
    measurementId: 'G-BYXSL1FNKT',
  );
}
